version: '3.9'

services:
  postgres:
    image: postgres:9.6.11
    ports:
      - 5432:5432
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    environment:
      - POSTGRES_PASSWORD=password
